package ml.jufa.backend.notification.entity;

public enum NotificationType {
    TRANSACTION_RECEIVED,
    TRANSACTION_SENT,
    TRANSACTION_FAILED,
    KYC_APPROVED,
    KYC_REJECTED,
    KYC_DOCUMENT_REQUIRED,
    LIMIT_WARNING,
    LIMIT_REACHED,
    QR_PAYMENT_RECEIVED,
    MERCHANT_RELATION_REQUEST,
    MERCHANT_RELATION_APPROVED,
    SYSTEM_ALERT,
    PROMOTIONAL
}
